baseURL: https://blog.delgaudio.dev
languageCode: en-us
title: mike's blog
author: Mike DelGaudio
theme: PaperMod
copyright: "Mike DelGaudio"

menu:
  main:
    - identifer: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifer: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifer: archives
      name: Archives
      url: /archives/
      weight: 30
    - identifer: search
      name: Search
      url: /search/
      weight: 40

params:
  homeInfoParams:
    Title: mike's blog
    Content: 👋 Hey all! This blog is where I share my findings along my journey across various technologies. I'll try to keep it interesting and teach you a couple new things.

  assets:
    theme_color: "#423"
    favicon: "/favicon.png"

  socialIcons:
    - name: "github"
      url: "https://github.com/mikedelgaudio"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/michael-delgaudio/"
    - name: "twitter"
      url: "https://twitter.com/delgaudiomike"
    - name: "youtube"
      url: "https://www.youtube.com/c/MikeDelGaudio"

  ShowCodeCopyButtons: true
  ShowReadingTime: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
